#Application
spring.application.name=api-gateway
spring.profiles.active=local
server.servlet.context-path=/api
server.port=8080
spring.main.web-application-type=servlet

#Caching
spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.redis.time-to-live=600000

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

#Routing
spring.cloud.gateway.server.webmvc.routes[0].id=user-service-route
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://user-service
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/users/**
