spring.application.name=feed_service
spring.profiles.active=local
server.servlet.context-path=/api
server.port=8083
spring.main.web-application-type=servlet

# Redis
spring.data.redis.host=${local.server.ip}
spring.data.redis.port=6379

# Eureka
eureka.client.service-url.defaultZone=http://${local.server.ip}:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=${local.server.ip}
eureka.instance.instance-id=${eureka.instance.ip-address}:${spring.application.name}:${server.port}